# Generated by Django 3.2.8 on 2021-10-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='date_of_retur',
            new_name='date_of_return',
        ),
    ]
